package psych.server.data.dao.dto;

// Generated Sep 14, 2014 9:06:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * GoalIconDTO generated by hbm2java
 */
public class GoalIconDTO implements java.io.Serializable {

	private String iconID;
	private String iconLink;

	public GoalIconDTO() {
	}

	public GoalIconDTO(String iconID) {
		this.iconID = iconID;
	}

	public GoalIconDTO(String iconID, String iconLink) {
		this.iconID = iconID;
		this.iconLink = iconLink;
	}

	public String getIconID() {
		return this.iconID;
	}

	public void setIconID(String iconID) {
		this.iconID = iconID;
	}

	public String getIconLink() {
		return this.iconLink;
	}

	public void setIconLink(String iconLink) {
		this.iconLink = iconLink;
	}

}
