package psych.server.data.dao.dto;

// Generated Sep 14, 2014 9:06:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ScoreDTO generated by hbm2java
 */
public class ScoreDTO implements java.io.Serializable {

	private String scoreID;
	private String scoreValStr;
	private Integer scoreValInt;
	private String scoreNote;
	private Date addDt;
	private Date lastUpdateDt;
	private GoalDTO goalDTO;

	public ScoreDTO() {
	}

	public ScoreDTO(GoalDTO goalDTO) {
		this.goalDTO = goalDTO;
	}

	public ScoreDTO(String scoreValStr, Integer scoreValInt, String scoreNote,
			Date addDt, Date lastUpdateDt, GoalDTO goalDTO) {
		this.scoreValStr = scoreValStr;
		this.scoreValInt = scoreValInt;
		this.scoreNote = scoreNote;
		this.addDt = addDt;
		this.lastUpdateDt = lastUpdateDt;
		this.goalDTO = goalDTO;
	}

	public String getScoreID() {
		return this.scoreID;
	}

	public void setScoreID(String scoreID) {
		this.scoreID = scoreID;
	}

	public String getScoreValStr() {
		return this.scoreValStr;
	}

	public void setScoreValStr(String scoreValStr) {
		this.scoreValStr = scoreValStr;
	}

	public Integer getScoreValInt() {
		return this.scoreValInt;
	}

	public void setScoreValInt(Integer scoreValInt) {
		this.scoreValInt = scoreValInt;
	}

	public String getScoreNote() {
		return this.scoreNote;
	}

	public void setScoreNote(String scoreNote) {
		this.scoreNote = scoreNote;
	}

	public Date getAddDt() {
		return this.addDt;
	}

	public void setAddDt(Date addDt) {
		this.addDt = addDt;
	}

	public Date getLastUpdateDt() {
		return this.lastUpdateDt;
	}

	public void setLastUpdateDt(Date lastUpdateDt) {
		this.lastUpdateDt = lastUpdateDt;
	}

	public GoalDTO getGoalDTO() {
		return this.goalDTO;
	}

	public void setGoalDTO(GoalDTO goalDTO) {
		this.goalDTO = goalDTO;
	}

}
